# Generated by Django 3.0.6 on 2020-07-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название товара')),
                ('cost', models.CharField(max_length=30, verbose_name='Цена товара')),
                ('shortdescription', models.TextField(verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание товара')),
            ],
        ),
    ]
